spring.application.name=AutoSales
spring.datasource.url=jdbc:postgresql://localhost:5432/autosales_DB
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
app.upload-dir=${user.dir}/uploads